#!/bin/sh

ln -s ~/GitHub/dotfiles/common-shell-confs ~/.common-shell-confs

ln -s ~/GitHub/dotfiles/bash-confs ~/.bash-confs

ln -s ~/.bash-confs/bashrc ~/.bashrc
ln -s ~/.bash-confs/bash_profile ~/.bash_profile

ln -s ~/GitHub/dotfiles/zsh-confs ~/.zsh-confs

ln -s ~/.zsh-confs/zshrc ~/.zshrc
ln -s ~/.zsh-confs/zprofile ~/.zprofile

ln -s ~/GitHub/dotfiles/git-confs ~/.git-confs
ln -s ~/.git-confs/gitconfig ~/.gitconfig

ln -s ~/GitHub/dotfiles/vim-confs/vimrc ~/.vimrc
