#!/bin/sh

# setup terminal colors
source ~/GitHub/conf-files/bin/colors

bins=('node-remove' 'shell-reset')
# bins=('shell-reset')
for bin in "${bins[@]}"
do
  source ~/GitHub/conf-files/bin/$bin
done

printf "\n${BLUE}❯ removing repos\n"
# repos=('bash-it', 'oh-my-zsh', 'conf-files')
repos=('oh-my-zsh')
for repo in "${repos[@]}"
do
  if [ -d ~/GitHub/$repo ]; then
    rm -rf ~/GitHub/$repo
    if [ $? == 0 ]; then
      printf "${GREEN}❯ removed ~/GitHub/$repo\n"
    fi
  fi
done
