#!/bin/sh

bins=('node-remove' 'shell-reset')
for bin in "${bins[@]}"
do
  source ~/GitHub/conf-files/bin/$bin
done

printf "\nremoving repos\n"
# repos=('bash-it', 'oh-my-zsh', 'conf-files')
repos=('oh-my-zsh')
for repo in "${repos[@]}"
do
  if [ -d ~/GitHub/$repo ]; then
    rm -rf ~/GitHub/$repo
    if [ $? == 0 ]; then
      printf "removed ~/GitHub/$repo\n"
    fi
  fi
done
