#!/bin/sh

# use colors, but only if connected to a terminal, and that terminal
# supports them.
if which tput >/dev/null 2>&1; then
  ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
  RED="$(tput setaf 1)"
  GREEN="$(tput setaf 2)"
  YELLOW="$(tput setaf 3)"
  BLUE="$(tput setaf 4)"
  BOLD="$(tput bold)"
  NORMAL="$(tput sgr0)"
else
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  BOLD=""
  NORMAL=""
fi

bins=('node-remove' 'shell-reset')
for bin in "${bins[@]}"
do
  source ~/GitHub/conf-files/bin/$bin
done

printf "\n${BLUE}❯ removing repos\n"
repos=('oh-my-zsh')
for repo in "${repos[@]}"
do
  if [ -d ~/GitHub/$repo ]; then
    rm -rf ~/GitHub/$repo
    if [ $? == 0 ]; then
      printf "${GREEN}❯ removed ~/GitHub/$repo\n"
    fi
  fi
done
