#!/bin/sh

# setup terminal colors
source ~/GitHub/conf-files/bin/colors

if [ ! -d ~/GitHub ]; then
  mkdir ~/GitHub
  if [ $? == 0 ]; then
    printf "\n${GREEN}❯ creating ~/GitHub directory${NORMAL}\n"
  fi
fi

printf "\n${BLUE}❯ cloning repos${NORMAL}\n"
printf "${YELLOW}❯ it may take few minutes ...\n"
# repos=('conf-files' 'oh-my-zsh' 'bash-it')
repos=('conf-files' 'oh-my-zsh')
for repo in "${repos[@]}"
do
  if [ ! -d ~/GitHub/$repo ]; then
    git clone git@github.com:sarbbottam/$repo.git ~/GitHub/$repo &>/dev/null
    if [ $? == 0 ]; then
      printf "${GREEN}❯ cloned $repo at ~/GitHub/$repo${NORMAL}\n"
    fi
  fi
done

printf "\n${BLUE}❯ creating symlink for oh-mys${NORMAL}\n"
# ohMys=('oh-my-zsh' 'bash-it');
ohMys=('oh-my-zsh');
for ohMy in "${ohMys[@]}"
do
  if [ -d ~/GitHub/$ohMy -a ! -L ~/.$ohMy ]; then
    ln -s  ~/GitHub/$ohMy ~/.$ohMy
    if [ $? == 0 ]; then
      printf "${GREEN}❯ created symlink ~/.$ohMy to ~/GitHub/$ohMy${NORMAL}\n"
    fi
  fi
done

bins=('shell-customize' 'node-setup')
# bins=('shell-customize')
for bin in "${bins[@]}"
do
  source ~/GitHub/conf-files/bin/$bin
done
