#!/bin/sh

if [ ! -d ~/GitHub ]; then
  printf "\ncreating ~/GitHub directory\n"
  mkdir ~/GitHub
fi

printf "\ncloning $repos\n"
# repos=('conf-files' 'oh-my-zsh' 'bash-it')
repos=('conf-files' 'oh-my-zsh')
for repo in "${repos[@]}"
do
  if [ ! -d ~/GitHub/$repo ]; then
    git clone git@github.com:sarbbottam/$repo.git ~/GitHub/$repo
    if [ $? == 0 ]; then
      printf "cloned at ~/GitHub/$repo\n"
    fi
  fi
done

bins=('shell-customize' 'node-setup')
for bin in "${bins[@]}"
do
  source ~/GitHub/conf-files/bin/$bin
done
