# Invoke .commons
source ~/.common-shell-confs/common

# Update PS1

# PS1='[`shell`] \[\033[31m\]\u\[\033[36m\] at \[\033[37m\]\h\[\033[35m\] in \[\033[32m\]\w \[\033[35m\]`git-branch` \n\[\033[32m\]吽\[\033[0m\] '

PS1='[`shell`] \[\033[31m\]\u\[\033[36m\] at \[\033[37m\]\h`yrootname`\[\033[35m\] in \[\033[32m\]\w \[\033[35m\]`git-branch``git-status` \n\[\033[32m\]吽\[\033[0m\] '
