#!/bin/sh

# Create ~/GitCorp directory, if not exists
homeDirs=('GitCorp' 'Sites' 'Downloads' '.vim/view' '.vim/autoload' '.vim/bundle');
for homeDir in "${homeDirs[@]}"
do
  if [ ! -d ~/$homeDir ]; then
    echo "creating ~/$homeDir"
    mkdir -p ~/$homeDir
    if [ $? == 0 ]; then
      echo "command executed: mkdir -p ~/$homeDir;"
      echo "created -p ~/$homeDir"
      echo
    fi
  fi
done

# Create ~/.vim/autoload/pathogen.vim, if not exists
if [ ! -f ~/.vim/autoload/pathogen.vim ]; then
  echo "creating ~/.vim/autoload/pathogen.vim"
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim;
  echo "command executed: curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim;"
  echo "created ~/.vim/autoload/pathogen.vim"
fi

# Backup existing files
existingConfFileNames=('.common-shell-confs' '.bash-confs' '.zsh-confs' '.git-confs' '.vim-confs' '.bashrc' '.bash_profile' '.zshrc' '.zprofile' '.gitconfig' 'gitignore_global' '.vimrc' '.screenrc' '.docker');
for existingConfFileName in "${existingConfFileNames[@]}"
do
  if [ -f ~/$existingConfFileName -o -d ~/$existingConfFileName -o -L ~/$existingConfFileName ]; then
    modifiedConfFileName=$existingConfFileName-prev;
    echo "backing up  ~/$existingConfFileName as ~/$modifiedConfFileName"
    mv ~/$existingConfFileName ~/$modifiedConfFileName
    echo "command executed: mv ~/$existingConfFileName ~/$modifiedConfFileName"
    echo "backed up  ~/$existingConfFileName as ~/$modifiedConfFileName"
    echo
  fi
done

# Create SymLinks
# ToDo Make the path relative
confDirNames=('common-shell-confs' 'bash-confs' 'zsh-confs' 'git-confs' 'vim-confs' 'docker-confs');
for confDirName in "${confDirNames[@]}"
do
  if [ -d ~/GitHub/conf-files/$confDirName ]; then
    echo "creating SymLink ~/.$confDirName to ~/GitHub/conf-files/$confDirName"
    ln -s  ~/GitHub/conf-files/$confDirName ~/.$confDirName
    echo "command executed: ln -s  ~/GitHub/conf-files/$confDirName ~/.$confDirName"
    echo "created SymLink ~/.$confDirName to ~/GitHub/conf-files/$confDirName"
    echo
  fi
done

confFileNames=('.bash-confs/bashrc' '.bash-confs/bash_profile' '.zsh-confs/zshrc' '.zsh-confs/zprofile' '.git-confs/gitconfig' '.git-confs/gitignore_global' '.vim-confs/vimrc' '.docker-confs/docker');
for confFileName in "${confFileNames[@]}"
do
  if [ -f ~/$confFileName ]; then
    symLinkName=.`echo ~/$confFileName | sed ' s!.*/!! ; s/"$// '`
    echo "creating SymLink ~/$symLinkName to ~/$confFileName"
    ln -s  ~/$confFileName ~/$symLinkName
    echo "command executed: ln -s  ~/$confFileName ~/$symLinkName"
    echo "created SymLink ~/$symLinkName to ~/$confFileName"
    echo
  fi
done
